[project]
name = "titanic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.127.0",
    "mypy",
    "pydantic>=2.12.5",
    "pytest>=9.0.2",
    "ruff",
    "sqlalchemy>=2.0.45",
    "uvicorn>=0.40.0",
]
